### ISSUE TITLE
Dustin, let's talk about switching to Stripe, 11-6-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#350]
Dustin, go ahead and do preliminary research about switching to Stripe. I want to set it up and be sure it works before I cancel First Data.

Check to be sure it will work with >

1. The Cart

2. With aMember

**Comment by dustinschaerer** [comment]
@david-huddleston We should be fine as far as the gateways go. 
Opencart Stripe extension: 
![stripe_op](https://user-images.githubusercontent.com/1232192/32904278-e80f10ca-caab-11e7-9584-5b0027a7d2c4.png)

Amember has it built in as a payment method, so nothing new is needed.
![stripe-am](https://user-images.githubusercontent.com/1232192/32904532-6431e6b4-caac-11e7-8cdd-49eaa18afcc8.png)

Since payments are absolutely crucial to work, I'd like us to sign up and get our account and API keys, set up a test account in amember streaming video and test it out.  Then look at switching the shopping cart over sometime next week, by Wednesday. I'd rather not do it on a Thursday or Friday.
