### ISSUE TITLE
Email the Order entry System developer, 12-6-17

### ISSUE THREAD

**Issue by david-huddleston** [soccerhelp/soccerhelp#451]
Dustin, as we discussed >

email to the Developer of the Order Entry and ask if there is an updated version that works with OpenCart 1.56 and includes Stripe

**Comment by dustinschaerer** [comment]
He responded to me but I had to ask more questions, I'll update when he responds.

**Comment by david-huddleston** [comment]
Great

**Comment by dustinschaerer** [comment]
@david-huddleston I got an updated version of the order entry system from Bobby, but it still didn't add Stripe automatically. It's weird, because the e4 gateway shows up and its not standard either. 

I decided to hit up Jonathon at Clear Thinking, the Stripe extension developer, and asked him what I have to do.  I'll keep you in the loop.
